### ISSUE TITLE
[ERROR] Traceback (most recent call last):

### ISSUE THREAD

**Issue by ceyhanmolla** [Azulinho/cryptobot#25]
[ERROR] Traceback (most recent call last):
  File "app.py", line 1241, in <module>
    cfg = yaml.safe_load(_f.read())
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/cryptobot/.venv/lib/python3.8-pyston2.3/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 33, column 1:
        BUY_AT_PERCENTAGE: -9.0
    ^

ERROR: 1

**Comment by Azulinho** [comment]
"found character '\t' that cannot start any token"

^ that's TAB
don't use tabs, google for YAML to learn about it.

and next time don't be rude and please ask a proper question

**Comment by ceyhanmolla** [comment]
It was not my intention to be rude to you. Thank you.
